# .github/workflows/ci.yml

name: Unsere CI Pieline

on: push

jobs:

  tests:
    runs-on: ubuntu-latest
    env:
          MEINE_VARIABLE: asef
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 15.x
        uses actions/setup-node@v1
        with:
            node-version: 15.x
      -run: npm install -g yarn
      -run: yarn install
      -run: yarn run test