# .github/workflows/ci.yml

name: Unsere CI Pipeline

on: push

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [13.x, 14.x, 15.x]
        services:
          redis: 
            image: redis
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install -g yarn
            - run: yarn install
            - run: yarn run test
              env:
                  MEINE_UMGEBUNGS_VARIABLE: ${{ secrets.MEINE_UMGEBUNGS_VARIABLE }}
            - name: Artefakte hochladen
              uses: actions/upload-artifact@v2
              with:
                  name: Mein-Test-Artefakt
                  path: ./package.json

    deploy:
        runs-on: ubuntu-latest
        needs: [tests]
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 15.x
              uses: actions/setup-node@v1
              with:
                  node-version: 15.x
            - run: npm install -g yarn
            - run: yarn install
            - run: yarn run test
